### PR TITLE
set PATH in zshenv instead of zshrc

### PR DESCRIPTION
**Pull request by gnowxilef**
@chriskuehl @NickImpicciche please review

### CODE REVIEW

**Comment by gnowxilef** [comment]
also @jvperrin

**Comment by jvperrin** [comment]
Looks good to me, but I'm not especially knowledgeable about zsh stuff. @matthew-mcallister might have something to say on this too.

**Comment by NickImpicciche** [comment]
Looks fine to me

**Comment by chriskuehl** [comment]
lgtm. if it works, shipit

**Comment by matthew-mcallister** [comment]
Tested the branch on meltdown, it works.

**Comment by nikhiljha** [comment]
this PR broke something in 2023. thanks @fawaf

**Comment by fawaf** [comment]
lol wut

**Comment by daradib** [comment]
Not a bad run

**Pull request merged**
