### PR TITLE
make xfce4 panel span multiple monitors

### PR DESCRIPTION
**Pull request by ja5087**
Currently, the xfce4 panel only stays on one monitor, which means it only displays on the left half on eruption with it's Picture By Picture mode. On other multi-monitor desktops, this is less important but still the panel isn't shown across both monitors. The default should be spanned in my opinion (and appealing to convention, is the default on macOS and Windows) and if users want old behavior they can toggle it in panel settings.

This PR sets the spanned option by default. Tested on cyclone.

### CODE REVIEW

**Comment by dkess** [comment]
Can you explain what exactly this does? Are you sure it's desirable? I don't remember having issues with xfce panels on dual monitors.

**Comment by ja5087** [comment]
Yep, sorry about that. Updated the desc.

**Comment by dkess** [comment]
If the same panel is spanning multiple monitors, I would say that looks weird and unusual on setups that aren't eruption. I would be indifferent if this configuration option were only on eruption, but personally I vote no if this is gonna affect all multi-monitor desktops.

If agree with you that this is a good change, feel free to merge over my objections.

**Comment by jvperrin** [comment]
I feel like a screenshot would be the best to show what this looks like (that or a picture from a camera so you can see the monitor splits)

**Comment by ja5087** [comment]
On Eruption it just looks like it spans the whole monitor. Here are some pictures from Typhoon. 

Here's what it looks like before:


Here's what it will look like after

**Pull request merged**
