### PR TITLE
Remove keur root

### PR DESCRIPTION
**Pull request by ethanhs**
o7

thanks for your service

### CODE REVIEW

**Comment by dkess** [comment]
07

**Review by keur — APPROVED** [review]
o7

**Comment by glee-** [comment]
o7On Sep 23, 2021 11:47 AM, Kevin Kuehler ***@***.***> wrote:
@keur approved this pull request.

o7

**Comment by ja5087** [comment]
o7

**Comment by nikhiljha** [comment]
o7

**Comment by kpengboy** [comment]
o7

**Pull request merged**
