### PR TITLE
Update ocf-suspend

### PR DESCRIPTION
**Pull request by singingtelegram**
addresses #1156.

### CODE REVIEW

**Comment by singingtelegram** [comment]
whoops, interface name on invasion is enp0s31f6 >:(

**Comment by kpengboy** [comment]
If the interface names varies from desktop to desktop, we could also consider disabling those "predictable" interface names. IIRC that is possible...

**Comment by singingtelegram** [comment]
that makes a lot of sense!

**Comment by singingtelegram** [comment]
I tried adding the net.ifnames=0 kernel flag, and now there are two interface entries:

```
enp0s31f6: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet [redacted]  netmask 255.255.255.0  broadcast 169.229.226.255
        ether [redacted]  txqueuelen 1000  (Ethernet)
        device interrupt 16  memory 0xf7200000-f7220000  

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 [redacted]  prefixlen 64  scopeid 0x20<link>
        inet6 [redacted, same last octet as IPv4]  prefixlen 64  scopeid 0x0<global>
        ether [redacted, same as above]  txqueuelen 1000  (Ethernet)
        RX packets 15214  bytes 1203377 (1.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1427  bytes 467522 (456.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  memory 0xf7200000-f7220000  
```

**Comment by singingtelegram** [comment]
(since enp0s31f6 is defined in /etc/network/interfaces.d by puppet)

**Comment by singingtelegram** [comment]
And subsequent puppet runs fail with "Warning: Facter: Command /opt/puppetlabs/puppet/cache/facts.d/ifaces-linked completed with the following stderr message: netlink error: no device matches name (offset 24)."

**Comment by singingtelegram** [comment]
primary iface name is stored in networking.primary

**Review by ethanhs — APPROVED** [review]
LGTM, should probably test it in person before merging though.

**Comment by singingtelegram** [comment]
No errors on invasion (my env) since I pushed the patch. Should be good for prod.

**Review by ethanhs — APPROVED** [review]

**Pull request merged**
