### PR TITLE
Add bzh key.

### PR DESCRIPTION
**Pull request by redplanks**

### CODE REVIEW

**Comment by redplanks** [comment]
Ah, let me create a new key associated with my berkeley email then.

**Comment by jvperrin** [comment]
Wait, you don't need to do that, you just put your Berkeley email in there so the backups get shared with your account, they are still encrypted with the key you put here. The first link I put you put the email associated with this key, and the second one you just put your account email, it's not related to the key at all.

**Comment by redplanks** [comment]
Ah, okay. Sorry for the confusion on my part.

**Comment by jvperrin** [comment]
That's fine, it's just confusing in that there are multiple lists of emails, but that they are for different purposes.

**Pull request merged**
