### PR TITLE
Update kadmind.acl

### PR DESCRIPTION
**Pull request by mcint**

### CODE REVIEW

**Comment by mcint** [comment]
```
$ ldapsearch -xLLL cn=ocfroot memberUid
dn: cn=ocfroot,ou=Group,dc=OCF,dc=Berkeley,dc=EDU
memberUid: abizer
memberUid: asai
memberUid: baisang
memberUid: bernardzhao
memberUid: bzh
memberUid: cooperc
memberUid: dkessler
memberUid: ethanhs
memberUid: fydai                                                                                                                            memberUid: jaw
memberUid: jkuki
memberUid: jvperrin
memberUid: kmo
memberUid: kpengboy
memberUid: kuoh
memberUid: mcint                                                                                                                            memberUid: mdcha
memberUid: minos
memberUid: njha
memberUid: rmxu
memberUid: ronitnath
memberUid: shasan
memberUid: snarain
memberUid: wporr
memberUid: yichizh
```

**Review by ethanhs — APPROVED** [review]
Oh oops I forgot to update this, thanks for doing that.

**Comment by mcint** [comment]
Hmm. Prometheus init_style function not defined. Recommends fixing something with `puppet catalog compile`.

Is anyone else familiar with this?  If not I'll fix in a day or two.

**Comment by dkess** [comment]
Could be related to #1080?

**Comment by ethanhs** [comment]
Yeah we seem to be getting weird prometheus errors from puppet but I'm not sure why, that change was 5 months ago, so I don't see why we would be starting to get them now?

**Comment by ethanhs** [comment]
(actually @dkess if you do end up streaming about OCF stuff, our Prometheus setup is something I am curious about)

**Comment by singingtelegram** [comment]
Superseded by #1134.

**Pull request closed without merging**
