### PR TITLE
remove jaws (also some munin config)

### PR DESCRIPTION
**Pull request by nikhiljha**
title

### CODE REVIEW

**Comment by singingtelegram** [comment]
I feel that the ping report could still be useful

**Comment by nikhiljha** [comment]
it's for munin and munin dne

**Comment by singingtelegram** [comment]
wait wait wait munin is still active

**Comment by singingtelegram** [comment]
there's just no web interface

**Comment by singingtelegram** [comment]
but the data collected complements with those from prometheus

**Comment by singingtelegram** [comment]
plz keep it for now

**Review by singingtelegram — APPROVED** [review]

**Pull request merged**
