### PR TITLE
ocf_kerberos: Add mcint /root and /admin principal privs

### PR DESCRIPTION
**Pull request by mcint**

### CODE REVIEW

**Comment by chriskuehl** [comment]
code lgtm if this was approved by an SM

**Comment by chriskuehl** [comment]
you'll need to be added to the ocfroot group too

also neither of those principles exist yet, you should do that in-person before merging this

**Comment by chriskuehl** [comment]
oops

**Comment by matthew-mcallister** [comment]
Closing and reopening the ticket seems to have broken the build check. Will have to investigate later.

**Pull request merged**
