### PR TITLE
Added redshift to list of packages

### PR DESCRIPTION
**Pull request by Baisang**
use redshift to get rid of nasty blue light from screen by opening a terminal and typing "redshift -O <desired color temperature>" eg. redshift -O 4700

### CODE REVIEW

**Comment by jvperrin** [comment]
Looks good to me, redshift is pretty nice. Might want to add `redshift-gtk` instead (or as well, not quite sure how the dependencies work there) so that it can have a gui to use.

**Comment by chriskuehl** [comment]
@ocfbot add to whitelist

**Comment by chriskuehl** [comment]
add to whitelist

**Comment by jvperrin** [comment]
Cool, I don't think I've met ocfbot before.

**Comment by chriskuehl** [comment]
jenkins, how does that work...

**Comment by Baisang** [comment]
So we tried the gtk version before on staff computer (which has regular redshift installed), but the GUI interface never worked. I think the new package for gtk redshift is gtk-redshift and I haven't tried it

**Comment by chriskuehl** [comment]
ok to test

**Comment by chriskuehl** [comment]
i give up, not sure how to get jenkins to run this

@Baisang it didn't run because you aren't in the ocf group
i just sent you an invite, if you accept it should work in the future

change looks good to me as well, I'll let @jvperrin decide to merge or not

**Comment by jvperrin** [comment]
Ah, I see, eruption has `redshift` and `gtk-redshift` installed already, I didn't realize that. I use `redshift-gtk` on my computer, and it works pretty well and depends on `redshift`, that might work well on the OCF computers too.

**Comment by jvperrin** [comment]
@Baisang Here, I'll install `redshift-gtk` on `eruption` manually and you can test it since you are still there

**Comment by jvperrin** [comment]
Unfortunately, looks like it's only in stretch or sid, so I think it's good to just go with what you have here.

**Pull request merged**
