### PR TITLE
Restart shellinabox on Wednesdays

### PR DESCRIPTION
**Pull request by ethanhs**

### CODE REVIEW

**Review by nikhiljha — APPROVED** [review]
it is wednesday my dudes

**Comment by kpengboy** [comment]
Wonder if there's an option to gracefully restart. Or if we can restart only on not detecting liveness...

**Comment by ethanhs** [comment]
> 
> 
> Wonder if there's an option to gracefully restart. Or if we can restart only on not detecting liveness...

For graceful restarting, I'm not sure. Restart on not detecting liveness is possible, but we really should do more work to do that in general for every service, so I'll push that off to a latter date.

**Comment by daradib** [comment]
Might be fixed by shellinabox/shellinabox@4f0ecc31ac6f985e0dd3f5a52cbfc0e9251f6361

**Comment by ethanhs** [comment]
@daradib interesting, unlikely to get backported on debian though, right?

**Comment by daradib** [comment]
For stretch, yeah. Debian drops "official" support for oldstable after stable release + 1 year. [LTS support](https://wiki.debian.org/LTS/) doesn't include backports. We could backport ourselves, but probably best to focus on upgrading servers to buster and bullseye.

**Pull request merged**
