### PR TITLE
update u2f/fido/hardware 2fa udev rules

### PR DESCRIPTION
**Pull request by tahabi**
it works now

### CODE REVIEW

**Comment by tahabi** [comment]
I'm not entirely sure this is necessary because we also have libu2f-host0 installed but it doesn't seem to hurt

**Comment by tahabi** [comment]
Oh this is just copied directly from the yubikey example config file. I
just `curl -o`'d it.

**Comment by jvperrin** [comment]
Yeah, I just think it would help to include a link to where it is from so if it needs updating it can be more easily done.

**Comment by tahabi** [comment]
Doesn't the terms of the license say we must include that disclaimer, especially since our code is licensed under GPLv3 and not 2.1, even though v3 includes the same disclaimer? I'm removing it per your recommendation, but I'm not sure. Something to ask @kpengboy perhaps?

**Comment by jvperrin** [comment]
Hmm, that's a good point, I guess it's fine to include then. I'd just prefer not to have extra license comments if we can link to the original and essentially say it's not ours in the first place, but the license is probably necessary?

Honestly I don't know much about all this licensing stuff though.

**Comment by tahabi** [comment]
According to [this](https://www.gnu.org/licenses/gpl-faq.en.html#v2v3Compatibility) we can include the code because it says GPVv2.1 or later, but I'm not sure if that means we still have to include the preamble. Honestly this tiny set of rules isn't even worth the time dedicated to figuring this licensing stuff out, lol.

**Comment by jvperrin** [comment]
Wait, so what is going on with this, is there a package that fixes it that could be used instead, or does it just work now?

**Pull request closed without merging**
