### PR TITLE
Version which dynamically updates the time left before logout

### PR DESCRIPTION
**Pull request by kpengboy**
I wrote another locker. This one has a dialog which updates the time remaining before lock/logout. I also cut the warning time from 5 minutes to 1 minute and raised the lock time to 9 minutes. One funky thing is that the dialog has an OK button which is permanently grayed out.
I haven't really tested this thing, mostly because I can't physically go to the lab right now and I don't want to bother with VNC in the next few days.

### CODE REVIEW

**Comment by kpengboy** [comment]
As of now, avalanche is on my puppet environment if anyone feels like testing it during the week

**Comment by chriskuehl** [comment]
@matthew-mcallister might want to take a look

**Comment by matthew-mcallister** [comment]
I should say I've tested these changes and they work and can be merged.

But, as far as personal preference goes, I think this looks slightly too tacky. Now that I've thought about it, I would rather see more subdued notify-send bubbles instead.

Further, in either case, any popup should say "xautolock" in the title so users know which process to kill to get rid of them, in case they are, e.g., watching a movie.

**Comment by kpengboy** [comment]
About the timeout: we could probably raise it, yes. I'm concerned that 5 minutes is too long, though. Maybe 3 minutes?

**Comment by chriskuehl** [comment]
closing this, was merged

**Pull request closed without merging**
