### PR TITLE
Puppet MUNGE authentication, needed for SLURM.

### PR DESCRIPTION
**Pull request by redplanks**
I've put munge.key into the private share folders for corruption and segfault.

### CODE REVIEW

**Comment by redplanks** [comment]
I did the syntax like `} -> next {` in compute.pp and controller.pp though.

**Comment by redplanks** [comment]
Bump. Which style should it be? In addition, the Puppet [style guide](https://puppet.com/docs/puppet/5.5/style_guide.html#chaining-arrow-syntax) recommends
```
Package['httpd']
-> Service['httpd']
```

**Comment by abizer** [comment]
+1 for following the style guide

**Comment by jvperrin** [comment]
It looks like it [does have a check for that](http://puppet-lint.com/checks/arrow_on_right_operand_line/) and that we have [disabled it](https://github.com/ocf/puppet/blob/2a06900abd36daa8049b4e586cd2c4150101f2fd/.pre-commit-config.yaml#L21). Some discussion about the disable is in https://github.com/ocf/puppet/pull/173.

**Comment by redplanks** [comment]
I'll change the arrow style to match the rest of the repository then.

**Pull request merged**
