### PR TITLE
Enable CJK IMEs on the desktops by default

### PR DESCRIPTION
**Pull request by ja5087**
Since this is in `skel` it won't impact users who already have their profile on the desktops, but all new users will have the CJK IMEs enabled by default. This covers the most common reasons people need to switch their keyboard layout, and the default is still English.

### CODE REVIEW

**Comment by dkess** [comment]
How was this file generated? Why does it have commented out options?

**Comment by ja5087** [comment]
It's just the profile file located in ~/.config/fcitx after you enable these input methods.

**Comment by ethanhs** [comment]
In general I am against extraneous commented out configs/code/etc. Is there a case where we would want to edit in the commented out options? Is it hard to find docs for this? If the answer to both of those questions is yes then I'm okay with leaving them in. Otherwise I think we should remove them.

**Comment by ja5087** [comment]
So I deleted out the commented out code but I'm not sure how I'd split the lines

**Comment by fydai** [comment]
That's fine, feel free to squash and merge yourself

**Pull request merged**
