### PR TITLE
Debian 11 changes #2

### PR DESCRIPTION
**Pull request by singingtelegram**

### CODE REVIEW

**Review by ethanhs — COMMENTED** [review]
Looks like there is a trailing whitespace but otherwise LGTM, thanks!

**Comment by ethanhs** [comment]
I think matchbox-keyboard could be a good replacement for florence, I believe it is used by the Raspberry Pi.

**Comment by singingtelegram** [comment]
what about onboard? I believe it's the default in Ubuntu. Where is the on screen keyboard used on our systems? I don't see an option to enable virtual keyboard on the logon prompt

**Comment by ethanhs** [comment]
> What about onboard? I think it's the default in Ubuntu.

I think that pulls in gnome which is a lot to install

**Review by ethanhs — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
