### PR TITLE
migrate puppetdb to managed postgres server

### PR DESCRIPTION
**Pull request by abizer**
my network connection is too tenuous right now for me to actually test this but it was working for a period of time during the original postgres testing run

### CODE REVIEW

**Comment by abizer** [comment]
there's still some weirdness where Java apparently refuses to accept that the Lets Encrypt cert is trusted and it takes an inordinately long amount of time to get the server to restart with the regular on-host postgres. The java version we have and java certfile both claim to trust Lets Encrypt so I'm not sure what's going on.

**Comment by ja5087** [comment]
I'm missing a lot of context on this but can anyone give a rundown of why this is better? Trying to see if it's worth finishing or we should close it eventually.

**Comment by jvperrin** [comment]
I think it's just one fewer postgres server to configure, since we don't need both a local postgres on thunder and a shared one on lethe. That being said, we haven't really had any troubles that I know of with the one on thunder and it's got ephemeral data anyway, so probably not a big deal to keep it around instead.

**Comment by nikhiljha** [comment]
We probably no longer need this, so closing it :)

**Pull request closed without merging**
