### PR TITLE
Add nvidia-settings to ocf_desktops

### PR DESCRIPTION
**Pull request by harrisonkuo**
Need nvidia-settings to remove screen tearing script, not sure about NUC.

### CODE REVIEW

**Comment by chriskuehl** [comment]
also probably only on desktops with nvidia? we have some logic for that already: https://github.com/ocf/puppet/blob/a4cda0ac13a0ac17abc58f82466f38b4b320b34c/modules/ocf_desktop/manifests/drivers.pp#L5-L14

**Comment by jvperrin** [comment]
`nvidia-settings` has a backported version too, so that one would probably work better and can just be added to this line: https://github.com/ocf/puppet/blob/master/modules/ocf_desktop/manifests/drivers.pp#L8

**Comment by harrisonkuo** [comment]
Woops, forgot about that one.

**Comment by matthew-mcallister** [comment]
Please don't close PRs prematurely, it's better to work on the existing branch so the discussion is preserved.

**Pull request closed without merging**
