### PR TITLE
Add texlive back to extrapackages

### PR DESCRIPTION
**Pull request by jameslzhu**
15516bc broke hkn's latex resume book generation, so this commit adds texlive back for use on apphost.

### CODE REVIEW

**Comment by dkess** [comment]
These shouldn't be in both files, can't we make this a proper `git revert` of the problematic commit?

**Comment by jameslzhu** [comment]
@dkess Oh my bad, I assumed the desktop puppet config was mutually exclusive. I'll do a git revert instead.

**Comment by abizer** [comment]
we don't need to do this, just install the package manually

**Comment by jameslzhu** [comment]
@dkess @abizer updated pr to revert 15516bc.

**Comment by nattofriends** [comment]
Why would you install a package manually in 2019

**Comment by jameslzhu** [comment]
Updating extrapackages means installing texlive on all machines with the config, do we have an apphost-specific manifest?

**Pull request merged**
