### PR TITLE
add buy spreadsheet shortlink

### PR DESCRIPTION
**Pull request by abizer**
going to RT to find this is super annoying + the link is shared only with officers@ so it should be safe

### CODE REVIEW

**Comment by kpengboy** [comment]
I don't see too much of a problem for opening up spreadsheet access to regular staff fwiw. Every allocation needs to be voted on by BoD anyway...

**Comment by matthew-mcallister** [comment]
What about adding this to `RESERVED_USERNAMES`?

I would just add a redirect to my `public_html` dir...

**Comment by abizer** [comment]
I think baisang owns the spreadsheet and would have to change the sharing rules as I don't have privs on it.

and @matthew-mcallister this is hopefully useful for more people than just me which is why I proposed adding it here...

**Comment by matthew-mcallister** [comment]
But anyone can visit a URL in your `public_html` dir, that's why it's called "public". Or `~staff/public_html` for that matter.

**Comment by Baisang** [comment]
closing this due to new sheet layout.

new forms will be open to all

**Comment by jvperrin** [comment]
(closed by #207)

**Pull request closed without merging**
