### PR TITLE
Remove pgp from Puppet

### PR DESCRIPTION
**Pull request by ethanhs**
RIP SKS :/

### CODE REVIEW

**Comment by fawaf** [comment]
curious why this is being removed.

**Comment by ethanhs** [comment]
@fawaf the SKS system had a poisoning attack and also has an attack where people greatly degraded performance by appending to prominent developer's keys. See e.g. https://www.gentoo.org/news/2019/07/03/sks-key-poisoning.html

**Comment by ethanhs** [comment]
Btw fixes #816

**Review by ja5087 — APPROVED** [review]
approved, the failing build doesn't look like this PR's fault. Feel free to merge when SMs approve.

**Pull request merged**
