### PR TITLE
add cooperc key and box email to backups

### PR DESCRIPTION
**Pull request by cg505**
I feel like people who have access to backups should have to sign something. Also, we should clean out the keys directory.

### CODE REVIEW

**Comment by dkess** [comment]
Are you sure you exported your key correctly? I'm not able to view the data using `gpg` or `pgpdump`.

**Comment by cg505** [comment]
maybe gpg on my laptop is too new uhhh

**Comment by cg505** [comment]
merged instead of rebase/squashing to preserve GPG signature on the commit

**Comment by abizer** [comment]
will the real cooperc please sign these commits
i repeat, will the real cooperc please sign these commits
we're going to have a problem here

**Pull request merged**
