### PR TITLE
Change pages -> sides in paper-genmon

### PR DESCRIPTION
**Pull request by fydai**
opstaff mentioned it was confusing

### CODE REVIEW

**Comment by ethanhs** [comment]
@keur, could you explain why you think so?

**Comment by keur** [comment]
@ethanhs it's going to say "10 sides left today". What is a side? It reads weird and probably will confuse people.

**Comment by ethanhs** [comment]
@keur, ah I can see that. Perhaps "10 sides of paper"?

**Comment by fydai** [comment]
Would you like to propose a better alternative?

**Pull request merged**
